### ISSUE TITLE
Default.tmPreferences not opening

### ISSUE THREAD

**Issue by doovers** [joomlapro/joomla3-sublime-snippets#9]
No access to the file from preferences menu. It opens a blank file with no ability to save. See screenshot for error message.

![screen shot 2014-01-31 at 12 00 55 pm](https://f.cloud.github.com/assets/5927611/2047080/34c2fa4a-8a13-11e3-9c8a-925c433e191e.png)

I had to create the file manually for it to work properly. 
(ST3 3059 for Mac)

**Comment by alebak** [comment]
You have to create a directory named "Joomla! 3.x Snippets"

**Comment by brunowego** [comment]
This project is not prepared for ST3. But you can contribute.

**Comment by brunowego** [comment]
Try:

``` bash
git clone https://github.com/joomlapro/joomla3-sublime-snippets.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Joomla\!\ 3.x\ Snippets
```

Works on OS X 10.10.
